# Generated by Django 4.2.7 on 2026-02-05 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrolerule',
            options={'verbose_name': 'Правило доступа', 'verbose_name_plural': 'Правила доступа'},
        ),
        migrations.AlterModelOptions(
            name='businesselement',
            options={'verbose_name': 'Бизнес-элемент', 'verbose_name_plural': 'Бизнес-элементы'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AddField(
            model_name='user',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Забанен до'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='create_permission',
            field=models.BooleanField(default=False, verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='delete_all_permission',
            field=models.BooleanField(default=False, verbose_name='Удаление всех'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='delete_permission',
            field=models.BooleanField(default=False, verbose_name='Удаление'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='authentication.businesselement', verbose_name='Элемент'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='read_all_permission',
            field=models.BooleanField(default=False, verbose_name='Чтение всех'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='read_permission',
            field=models.BooleanField(default=False, verbose_name='Чтение'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='authentication.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='update_all_permission',
            field=models.BooleanField(default=False, verbose_name='Обновление всех'),
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='update_permission',
            field=models.BooleanField(default=False, verbose_name='Обновление'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='has_owner_field',
            field=models.BooleanField(default=False, verbose_name='Есть поле владельца'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='session',
            name='access_expires_at',
            field=models.DateTimeField(verbose_name='Истекает access токен'),
        ),
        migrations.AlterField(
            model_name='session',
            name='access_jti',
            field=models.CharField(max_length=255, unique=True, verbose_name='Access JTI'),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 12, 14, 2, 43, 373952, tzinfo=datetime.timezone.utc), verbose_name='Истекает refresh токен'),
        ),
        migrations.AlterField(
            model_name='session',
            name='refresh_jti',
            field=models.CharField(max_length=255, unique=True, verbose_name='Refresh JTI'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Суперпользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Назначена'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначена'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='authentication.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
